export const wordle: { puzzleNumber: number; words: string[] }[] = [
  // Apr 26
  { puzzleNumber: 1394, words: ["agony", "radar", "scath", "clash"] },
  { puzzleNumber: 1393, words: ["jacks", "knive", "knoll", "known"] },
  { puzzleNumber: 1392, words: ["clump", "being", "deign", "genie"] },
  { puzzleNumber: 1391, words: ["paced", "emits", "feely", "gorge", "ounce", "ozone"] },
  { puzzleNumber: 1390, words: ["dummy", "ratty", "artsy"] },
  { puzzleNumber: 1389, words: ["plays", "spart", "spate"] },
  { puzzleNumber: 1388, words: ["paris", "tired", "dirge"] },
  { puzzleNumber: 1387, words: ["focus", "snowy", "spore", "sloot", "stook", "stood"] },
  { puzzleNumber: 1386, words: ["acres", "parry", "moria", "moral"] },
  { puzzleNumber: 1385, words: ["cuffs", "spoil", "asset", "ashed", "ashen"] },
  { puzzleNumber: 1384, words: ["pages", "sense", "crest"] },
  { puzzleNumber: 1383, words: ["avert", "truck", "turns", "turfy", "turbo"] },
  { puzzleNumber: 1382, words: ["hardy", "shame", "cheat", "wheat"] },
  { puzzleNumber: 1381, words: ["allot", "palls", "villa"] },
  { puzzleNumber: 1380, words: ["nulls", "grime", "chomp", "mommy", "foamy"] },
  { puzzleNumber: 1379, words: ["freed", "group", "crass", "brink", "krill"] },
  { puzzleNumber: 1378, words: ["blind", "ninth", "finer", "singe", "since"] },
  {
    puzzleNumber: 1377,
    words: ["okays", "sprat", "stear", "smear", "spear", "shear"],
  },
  {
    puzzleNumber: 1376,
    words: ["freak", "swath", "staid", "stags", "stamp", "stall"],
  },
  { puzzleNumber: 1375, words: ["craps", "corse", "curse"] },
  { puzzleNumber: 1374, words: ["point", "serve", "beech", "weedy", "jewel"] },
  { puzzleNumber: 1373, words: ["sates", "quack", "album", "awful", "afoul"] },
  {
    puzzleNumber: 1372,
    words: ["glass", "vouch", "ronin", "pommy", "toffy", "dotty", "booty"],
  },
  { puzzleNumber: 1371, words: ["enact", "plods", "sorry"] },
  { puzzleNumber: 1370, words: ["input", "barge", "force", "verse"] },
  { puzzleNumber: 1369, words: ["sated", "steem", "sleet", "skeet", "sheet"] },
  { puzzleNumber: 1368, words: ["crows", "monad", "poddy", "dopey"] },
  { puzzleNumber: 1367, words: ["extra", "artsy", "ratch", "ratan", "ratio"] },
  { puzzleNumber: 1366, words: ["brank", "lunet", "nudge"] },
  { puzzleNumber: 1365, words: ["droop", "bunch", "bases", "baste"] },
  { puzzleNumber: 1364, words: ["today", "paves", "spawn", "spark"] },
  { puzzleNumber: 1363, words: ["clack", "laser", "lasso"] },
  { puzzleNumber: 1362, words: ["spans", "scape", "stamp"] },
  { puzzleNumber: 1361, words: ["brood", "diddy", "ladle"] },
  { puzzleNumber: 1360, words: ["merde", "scene", "clepe", "piece"] },
  { puzzleNumber: 1359, words: ["verso", "these", "chase"] },
  { puzzleNumber: 1358, words: ["yowza", "tared", "tract", "track"] },
  {
    puzzleNumber: 1357,
    words: ["extra", "tends", "stole", "shute", "smite", "spite"],
  },
  { puzzleNumber: 1356, words: ["wonts", "grime", "greed"] },
  { puzzleNumber: 1355, words: ["reave", "waved", "faves", "gavel", "navel"] },
  { puzzleNumber: 1354, words: ["worse", "bumpy", "until", "laugh", "fluff"] },
  { puzzleNumber: 1353, words: ["boofy", "croon", "groom", "troop"] },
  { puzzleNumber: 1352, words: ["kapow", "assay", "antre", "avert", "alert"] },
  { puzzleNumber: 1351, words: ["mouse", "scrum"] },
  { puzzleNumber: 1350, words: ["shims", "choke", "cheek", "check"] },
  { puzzleNumber: 1349, words: ["loser", "sevir", "shear", "spear"] },
  { puzzleNumber: 1348, words: ["feats", "melty", "betty", "genty", "deity"] },
  {
    puzzleNumber: 1347,
    words: ["stump", "under", "ghoul", "quick", "buffy", "fuzzy"],
  },
  { puzzleNumber: 1346, words: ["mound", "dolls", "lordy", "lodge"] },
  { puzzleNumber: 1345, words: ["junta", "feebs", "error", "dryer"] },
  { puzzleNumber: 1344, words: ["minus", "nerdy", "blond", "gland"] },
  { puzzleNumber: 1343, words: ["ladle", "steer", "other", "otter"] },
  { puzzleNumber: 1342, words: ["spews", "creed", "creek", "cream"] },
  {
    puzzleNumber: 1341,
    words: ["loony", "blows", "gloam", "flour", "plock", "clove"],
  },
  { puzzleNumber: 1340, words: ["cruft", "needs", "dinge", "indie"] },
  { puzzleNumber: 1339, words: ["masts", "trace", "trawl", "trail"] },
  {
    puzzleNumber: 1338,
    words: ["blams", "snake", "stare", "spade", "shave", "suave"],
  },
  {
    puzzleNumber: 1337,
    words: ["whump", "grind", "broke", "frock", "croak", "crock", "crook"],
  },
  {
    puzzleNumber: 1336,
    words: ["harms", "peely", "kinky", "diddy", "dizzy", "divvy", "ditty"],
  },
  { puzzleNumber: 1335, words: ["snarf", "raged", "rotal", "rumba"] },
  { puzzleNumber: 1334, words: ["carol", "roche", "score"] },
  {
    puzzleNumber: 1333,
    words: ["voice", "bowls", "boots", "boars", "bobos", "bongs", "bonus"],
  },
  { puzzleNumber: 1332, words: ["caulk", "prime", "doped", "steep"] },
  { puzzleNumber: 1331, words: ["nouns", "slice", "sprat", "staff", "swath"] },
  { puzzleNumber: 1330, words: ["grand", "style", "bloop", "pilum", "pupil"] },
  { puzzleNumber: 1329, words: ["luger", "saint", "booth", "tooth"] },
  {
    puzzleNumber: 1328,
    words: ["curly", "berry", "worry", "marry", "tarry", "harry", "parry"],
  },
  { puzzleNumber: 1327, words: ["chode", "frite", "spare", "gurge", "revue"] },
  { puzzleNumber: 1326, words: ["freet", "reals", "prove", "whore", "chore"] },
  { puzzleNumber: 1325, words: ["chaps", "grind", "riley", "river", "rivet"] },
  { puzzleNumber: 1324, words: ["compo", "roans", "boast", "toast"] },
  { puzzleNumber: 1323, words: ["quork", "weald", "lazes", "salse", "false"] },
  {
    puzzleNumber: 1322,
    words: ["balks", "privy", "toner", "fewer", "ruder", "udder"],
  },
  { puzzleNumber: 1321, words: ["gnash", "drive", "rivet", "lover", "fever"] },
  { puzzleNumber: 1320, words: ["sanga", "snoop", "stunk", "shunt"] },
  { puzzleNumber: 1319, words: ["sooth", "sense", "sunny"] },
  { puzzleNumber: 1318, words: ["egads", "shorn", "rusty", "prism", "crisp"] },
  {
    puzzleNumber: 1317,
    words: ["scuzz", "dates", "flays", "grams", "brans", "brass"],
  },
  { puzzleNumber: 1316, words: ["bugle", "dance", "score", "crime", "crepe"] },
  { puzzleNumber: 1315, words: ["boded", "miles", "payer", "upper"] },
  { puzzleNumber: 1314, words: ["adder", "reaps", "realm", "reach"] },
  { puzzleNumber: 1313, words: ["grout", "bling", "vying", "aging", "icing"] },
  {
    puzzleNumber: 1312,
    words: ["goody", "bones", "moler", "cover", "tower", "power", "rower"],
  },
  { puzzleNumber: 1311, words: ["blues", "salty", "silly"] },
  { puzzleNumber: 1310, words: ["codex", "prove", "prone", "probe", "prose"] },
  { puzzleNumber: 1309, words: ["brink", "knack"] },
  { puzzleNumber: 1308, words: ["clamp", "hacks", "farce", "fancy"] },
  { puzzleNumber: 1307, words: ["bitte", "sworn", "gloam", "cloak"] },
  { puzzleNumber: 1306, words: ["yoyos", "board", "focal", "total"] },
  { puzzleNumber: 1305, words: ["makes", "croon", "bling", "dingy"] },
  { puzzleNumber: 1304, words: ["trite", "drunk", "frogs", "crawl"] },
  { puzzleNumber: 1303, words: ["dorts", "braid"] },
  {
    puzzleNumber: 1302,
    words: ["curny", "rager", "paler", "waver", "water", "wafer"],
  },
  { puzzleNumber: 1301, words: ["lolly", "range", "scram", "after", "draft"] },
  { puzzleNumber: 1300, words: ["hovel", "slips", "lurks", "malts", "atlas"] },
  { puzzleNumber: 1299, words: ["lumps", "grand", "ribby", "cyber"] },
  { puzzleNumber: 1298, words: ["recur", "craig", "crios", "crith", "crimp"] },
  { puzzleNumber: 1297, words: ["smith", "heard", "phage", "cheap"] },
  { puzzleNumber: 1296, words: ["runny", "serve", "trice", "afore", "glare"] },
  { puzzleNumber: 1295, words: ["bread", "ethos", "shoes", "chose"] },
  {
    puzzleNumber: 1294,
    words: ["vizir", "piler", "cider", "biter", "wiser", "fixer", "finer"],
  },
  { puzzleNumber: 1293, words: ["entry", "rends", "neral", "nerve"] },
  { puzzleNumber: 1292, words: ["lisps", "lever", "lemur"] },
  { puzzleNumber: 1291, words: ["addle", "cache", "grate", "stare"] },
  {
    puzzleNumber: 1290,
    words: ["youse", "hired", "rhino", "train", "brain", "grain"],
  },
  {
    puzzleNumber: 1289,
    words: ["again", "maker", "maths", "madly", "mapou", "mambo"],
  },
  { puzzleNumber: 1288, words: ["golfs", "brine", "racer", "decry"] },
  {
    puzzleNumber: 1287,
    words: ["tines", "voila", "magic", "braid", "wuxia", "affix"],
  },
  {
    puzzleNumber: 1286,
    words: ["comes", "sense", "sithe", "shade", "shave", "share"],
  },
  { puzzleNumber: 1285, words: ["annal", "labor", "salut", "dalle", "maple"] },
  { puzzleNumber: 1284, words: ["silly", "dumbs", "beans", "bones"] },
  { puzzleNumber: 1283, words: ["weary", "allot", "cavas", "sanga", "sauna"] },

  { puzzleNumber: 1282, words: ["scrab", "barky", "brain", "brawn"] },
  {
    puzzleNumber: 1281,
    words: ["poohs", "fried", "medal", "ealed", "glade", "blade"],
  },
  { puzzleNumber: 1280, words: ["shirk", "flesh", "flash"] },
  { puzzleNumber: 1279, words: ["wight", "bawls", "scowl"] },
  { puzzleNumber: 1278, words: ["fanon", "croak", "adobe", "boats", "boast"] },
  { puzzleNumber: 1277, words: ["dopey", "jazzy", "grimy", "sucky", "funky"] },
  { puzzleNumber: 1276, words: ["rotor", "tasty", "innit", "bidet", "eight"] },
  {
    puzzleNumber: 1275,
    words: ["tofus", "model", "power", "boner", "borer", "boxer"],
  },
  {
    puzzleNumber: 1274,
    words: ["group", "thing", "sling", "aging", "being", "dying", "vying"],
  },
  { puzzleNumber: 1273, words: ["press", "point", "pavvy", "plumb"] },
  { puzzleNumber: 1272, words: ["actin", "ratio", "patio"] },
  { puzzleNumber: 1271, words: ["glyph", "bling", "clang", "flung"] },
  { puzzleNumber: 1270, words: ["vital", "saner", "meany", "hyena"] },
  { puzzleNumber: 1269, words: ["annoy", "bumpy", "silty", "hilly"] },
  { puzzleNumber: 1268, words: ["shart", "shool", "shone", "shove"] },
  { puzzleNumber: 1267, words: ["bumps", "react", "envoy", "ennog", "endow"] },
  { puzzleNumber: 1266, words: ["oscar", "crude", "crith", "crypt"] },
  { puzzleNumber: 1227, words: ["spake", "snaky", "shaky"] },
  { puzzleNumber: 1226, words: ["scrip", "igloo", "glide", "guile"] },
  { puzzleNumber: 1225, words: ["misty", "magma", "maned", "maple", "mauve"] },
  { puzzleNumber: 1224, words: ["alike", "brats", "gammy", "magma", "dogma"] },
  { puzzleNumber: 1223, words: ["hyped", "hippo"] },
  { puzzleNumber: 1222, words: ["tanks", "crock", "clock", "chock"] },
  { puzzleNumber: 1221, words: ["blurb", "slope", "slant", "slang"] },
  { puzzleNumber: 1220, words: ["amour", "feint", "piths", "witch"] },
  { puzzleNumber: 1219, words: ["bylaw", "brews", "brown"] },
  { puzzleNumber: 1218, words: ["wands", "swell", "twist"] },
  { puzzleNumber: 1217, words: ["timer", "evens", "webby", "ledgy", "jelly"] },
  { puzzleNumber: 1216, words: ["opted", "peely", "peril", "pearl"] },
  { puzzleNumber: 1215, words: ["opted", "scope", "posse", "poise"] },
  { puzzleNumber: 1214, words: ["aptly", "oppos", "spine"] },
  { puzzleNumber: 1213, words: ["reuse", "glide", "tithe", "niche"] },
  { puzzleNumber: 1212, words: ["repun", "noisy", "joint", "going"] },
  { puzzleNumber: 1211, words: ["deals", "snort", "borks", "visor"] },
  { puzzleNumber: 1210, words: ["ravin", "venus", "ovine", "event"] },
  { puzzleNumber: 1209, words: ["flash", "tried", "miner"] },
  { puzzleNumber: 1208, words: ["taupe", "thuds", "truck", "trull", "truly"] },
  { puzzleNumber: 1207, words: ["voted", "otter", "octet"] },
  { puzzleNumber: 1206, words: ["tater", "soupy", "lying", "flyin", "vinyl"] },
  {
    puzzleNumber: 1205,
    words: ["namer", "slate", "glade", "flake", "place", "blaze"],
  },
  { puzzleNumber: 1204, words: ["bonza", "oncer", "knots", "snoop"] },
  { puzzleNumber: 1203, words: ["pandy", "routs", "shite", "sixth"] },
  { puzzleNumber: 1202, words: ["avers", "metro", "berry", "weird"] },
  { puzzleNumber: 1201, words: ["solar", "lapse", "easle", "easel"] },
  { puzzleNumber: 1200, words: ["morin", "leads", "gaudy", "bawdy"] },
  { puzzleNumber: 1199, words: ["curls", "spoon", "snift", "sense", "sandy"] },
  {
    puzzleNumber: 1198,
    words: ["thrum", "bears", "raced", "clear", "great", "freak", "wreak"],
  },
  { puzzleNumber: 1197, words: ["every", "wrong", "crown", "frown"] },
  { puzzleNumber: 1196, words: ["waste", "still", "snout", "shout"] },
  { puzzleNumber: 1195, words: ["admin", "rerun", "colon", "spoon"] },
  { puzzleNumber: 1194, words: ["gayer", "money", "piley", "divey", "dicey"] },
  {
    puzzleNumber: 1193,
    words: ["skier", "viner", "cider", "tiler", "hiper", "fiber"],
  },
  { puzzleNumber: 1192, words: ["mivvy", "innit", "stint"] },
  {
    puzzleNumber: 1191,
    words: ["boson", "trier", "weedy", "clame", "value", "halve"],
  },
  {
    puzzleNumber: 1190,
    words: ["volks", "whare", "drain", "brant", "trant", "grant"],
  },
  {
    puzzleNumber: 1189,
    words: ["teste", "whelm", "grief", "paper", "nuder", "joker", "corer"],
  },
  { puzzleNumber: 1188, words: ["birth", "total", "stays", "mated", "gamut"] },
  { puzzleNumber: 1187, words: ["blurb", "rotor", "servo", "prone"] },
  { puzzleNumber: 1186, words: ["mylar", "phony", "gusty"] },
  { puzzleNumber: 1185, words: ["forth", "early", "dares", "garre", "carve"] },
  { puzzleNumber: 1184, words: ["vague", "frith", "polly", "moody", "mommy"] },
  { puzzleNumber: 1183, words: ["slant", "front", "point", "joint"] },
  { puzzleNumber: 1182, words: ["fault", "flume", "flour"] },
  {
    puzzleNumber: 1181,
    words: ["olden", "patel", "lamer", "layer", "laser", "lager"],
  },
  { puzzleNumber: 1180, words: ["caper", "daily", "wagon"] },
  { puzzleNumber: 1179, words: ["count", "wears", "sheep", "shelf", "shell"] },
  {
    puzzleNumber: 1178,
    words: ["steak", "brine", "regex", "flued", "dopey", "modem"],
  },
  { puzzleNumber: 1177, words: ["dreck", "clads", "cloud"] },
  {
    puzzleNumber: 1176,
    words: ["sober", "diner", "wider", "hider", "cider", "rider"],
  },
  { puzzleNumber: 1175, words: ["shift", "claim", "drain", "grain", "brain"] },
  { puzzleNumber: 1174, words: ["sider", "thing", "faith"] },
  { puzzleNumber: 1173, words: ["foggy", "nears", "bland", "chant", "thank"] },
  { puzzleNumber: 1172, words: ["trout", "torso", "torch"] },
  {
    puzzleNumber: 1171,
    words: ["croon", "river", "marry", "barry", "larry", "harry"],
  },
  { puzzleNumber: 1170, words: ["birds", "glade", "caddy", "pandy", "handy"] },
  { puzzleNumber: 1169, words: ["alpha", "razor", "quack", "began", "steam"] },
  { puzzleNumber: 1168, words: ["beans", "sense", "seven"] },
  { puzzleNumber: 1167, words: ["artsy", "souls", "spode", "shone", "smoke"] },
  { puzzleNumber: 1166, words: ["exist", "dress", "press"] },
  {
    puzzleNumber: 1165,
    words: ["faddy", "forty", "funny", "fuzzy", "fugly", "fully"],
  },
  {
    puzzleNumber: 1164,
    words: ["meiny", "serfs", "pedal", "weave", "heath", "beaut"],
  },
  { puzzleNumber: 1163, words: ["meint", "ender", "panel", "cones", "honey"] },
  {
    puzzleNumber: 1162,
    words: ["badly", "often", "piece", "sects", "gecko", "recur"],
  },
  { puzzleNumber: 1161, words: ["props", "trove", "groan", "croak", "broad"] },
  { puzzleNumber: 1160, words: ["belee", "watch", "harsh"] },
  { puzzleNumber: 1159, words: ["money", "raids", "frats", "grabs", "brass"] },
  {
    puzzleNumber: 1158,
    words: ["gazer", "metal", "blade", "apple", "ahole", "anile", "aisle"],
  },
  { puzzleNumber: 1157, words: ["navel", "repel", "rebel"] },
  { puzzleNumber: 1156, words: ["slurp", "cheat", "bidet", "debit"] },
  { puzzleNumber: 1155, words: ["prays", "crate", "fraud", "drain", "drawn"] },
  { puzzleNumber: 1154, words: ["coves", "other", "older", "owner"] },
  { puzzleNumber: 1153, words: ["lower", "rears", "retry", "rerun"] },
  { puzzleNumber: 1152, words: ["okays", "flier", "given", "wizen", "widen"] },
  { puzzleNumber: 1151, words: ["adhoc", "wares", "fanny", "faint"] },
  {
    puzzleNumber: 1150,
    words: ["banal", "truck", "quids", "pussy", "gushy", "mushy"],
  },
  { puzzleNumber: 1149, words: ["sewer", "scant", "shout", "spout"] },
  { puzzleNumber: 1148, words: ["matin", "anode", "snake", "knave"] },
  {
    puzzleNumber: 1147,
    words: ["razer", "thigh", "bowls", "lucky", "plunk", "flunk"],
  },
  { puzzleNumber: 1146, words: ["saint", "titty", "lithe"] },
  {
    puzzleNumber: 1145,
    words: ["payer", "round", "snort", "groin", "frown", "brown", "crown"],
  },
  { puzzleNumber: 1144, words: ["avast", "stare", "stale", "stake"] },
  { puzzleNumber: 1143, words: ["snark", "skate"] },
  {
    puzzleNumber: 1142,
    words: ["house", "exact", "tenet", "pipet", "bidet", "filet"],
  },
  { puzzleNumber: 1141, words: ["space", "trine", "wrote", "brute"] },
  { puzzleNumber: 1140, words: ["stoke", "flair", "gulpy", "mulch"] },
  { puzzleNumber: 1139, words: ["media", "deads", "decal", "delay"] },
  { puzzleNumber: 1138, words: ["whelm", "meant", "prime"] },
  {
    puzzleNumber: 1137,
    words: ["traps", "magma", "waved", "bacon", "fanny", "janky", "lanky"],
  },
  { puzzleNumber: 1136, words: ["pizza", "turds", "store", "stork", "storm"] },
  { puzzleNumber: 1135, words: ["rinse", "groan", "adorn", "acorn"] },
  { puzzleNumber: 1134, words: ["humpy", "cinch", "there", "share", "shore"] },
  { puzzleNumber: 1133, words: ["final", "snide", "twine", "noise", "neigh"] },
  { puzzleNumber: 1132, words: ["carve", "moths", "skill", "skiff"] },
  { puzzleNumber: 1131, words: ["dreck", "cells", "scape", "scone"] },
  { puzzleNumber: 1130, words: ["babby", "fluff", "eerie", "denim", "medic"] },
  {
    puzzleNumber: 1129,
    words: ["today", "savvy", "sally", "samey", "sappy", "saggy", "saucy"],
  },
  { puzzleNumber: 1128, words: ["scant", "caper", "hacky", "cacao", "macaw"] },
  { puzzleNumber: 1127, words: ["junky", "noise", "titan", "inane", "anvil"] },
  { puzzleNumber: 1126, words: ["moats", "shied", "essay", "ensue"] },
  {
    puzzleNumber: 1125,
    words: ["verve", "creds", "ripen", "water", "bower", "lower"],
  },
  {
    puzzleNumber: 1124,
    words: ["votes", "sneak", "seamy", "spade", "scare", "scale"],
  },
  { puzzleNumber: 1123, words: ["ploys", "glare", "blade", "flame", "flake"] },
  { puzzleNumber: 1122, words: ["epics", "larch", "chalk"] },
  {
    puzzleNumber: 1121,
    words: ["egger", "seedy", "belle", "weave", "seine", "penne"],
  },
  { puzzleNumber: 1120, words: ["squee", "ettin", "reply", "feral"] },
  { puzzleNumber: 1119, words: ["cramp", "spire", "super"] },
  { puzzleNumber: 1118, words: ["thumb", "group", "quine", "juice"] },
  { puzzleNumber: 1117, words: ["kinda", "allay", "aware", "awash"] },
  { puzzleNumber: 1116, words: ["tough", "porch"] },
  { puzzleNumber: 1115, words: ["dumps", "frack", "fiery", "forte"] },
  { puzzleNumber: 1114, words: ["abyss", "proto", "prone", "prong"] },
  { puzzleNumber: 1113, words: ["mappy", "batch", "tacts", "carat", "cadet"] },
  { puzzleNumber: 1112, words: ["coper", "peach", "spice", "speck"] },
  { puzzleNumber: 1111, words: ["robin", "dealt", "ghast", "shaft"] },
  { puzzleNumber: 1110, words: ["quits", "ready", "nerdy"] },
  { puzzleNumber: 1109, words: ["tripe", "stile", "quite"] },
  { puzzleNumber: 1108, words: ["pupal", "fried", "swoon"] },
  { puzzleNumber: 1107, words: ["mucho", "grand", "flies", "jiffy"] },
  { puzzleNumber: 1106, words: ["aleph", "bears", "eaved", "matey", "cameo"] },
  { puzzleNumber: 1105, words: ["older", "ruins", "taunt", "gaunt"] },
  { puzzleNumber: 1104, words: ["pilot", "laugh", "fleas", "blare"] },
  { puzzleNumber: 1103, words: ["waltz", "ardor", "seamy", "snake", "shape"] },
  { puzzleNumber: 1102, words: ["heron", "baton", "mason", "wagon", "canon"] },
  { puzzleNumber: 1101, words: ["goose", "short", "scold", "scoff"] },
  { puzzleNumber: 1100, words: ["campy", "roles", "fight", "thigh"] },
  { puzzleNumber: 1099, words: ["relax", "wheat", "spade", "adage"] },
  { puzzleNumber: 1098, words: ["filet", "essay", "beano", "zebra"] },
  {
    puzzleNumber: 1097,
    words: ["blitz", "quack", "mopes", "heron", "erode", "drove"],
  },
  {
    puzzleNumber: 1096,
    words: ["adage", "plank", "claim", "blast", "flash", "slash"],
  },
  { puzzleNumber: 1095, words: ["funds", "dread", "order"] },
  { puzzleNumber: 1094, words: ["zippy", "quart", "axles", "genoa", "knead"] },
  { puzzleNumber: 1093, words: ["virus", "savor"] },
  { puzzleNumber: 1092, words: ["waits", "verge", "gnome", "bugle"] },
  { puzzleNumber: 1091, words: ["chump", "react", "evict", "edict"] },
  { puzzleNumber: 1090, words: ["depot", "print", "paint"] },
  { puzzleNumber: 1089, words: ["mange", "needs", "skein", "spent", "scent"] },
  { puzzleNumber: 1088, words: ["prion", "rates", "strew", "terse"] },
  { puzzleNumber: 1087, words: ["plows", "ebony", "doted", "cover"] },
  { puzzleNumber: 1086, words: ["creed", "froth", "organ", "brios", "prior"] },
  { puzzleNumber: 1085, words: ["enact", "noisy", "grind"] },
  { puzzleNumber: 1084, words: ["parch", "prism", "prone", "proud"] },
  { puzzleNumber: 1083, words: ["valet", "vault"] },
  { puzzleNumber: 1082, words: ["mines", "snort", "unset", "angst"] },
  { puzzleNumber: 1081, words: ["ponty", "named", "skins", "slung", "swung"] },
  {
    puzzleNumber: 1080,
    words: ["willy", "entre", "bason", "vaunt", "nappa", "manga"],
  },
  { puzzleNumber: 1079, words: ["ample", "stone", "niche", "hence"] },
  {
    puzzleNumber: 1078,
    words: ["freak", "glove", "elops", "loxed", "below", "melon"],
  },
  { puzzleNumber: 1077, words: ["corny", "raise", "lever", "egger", "ether"] },
  { puzzleNumber: 1076, words: ["loopy", "otter", "ochre", "orbit", "organ"] },
  { puzzleNumber: 1075, words: ["party", "brock", "drone", "frows", "groom"] },
  { puzzleNumber: 1074, words: ["lefty", "trist", "straw", "stars", "stark"] },
  { puzzleNumber: 1073, words: ["leafs", "track", "drain", "gravy", "bravo"] },
  {
    puzzleNumber: 1072,
    words: ["yanks", "chars", "chats", "chaps", "chais", "chads", "chaos"],
  },
  { puzzleNumber: 1071, words: ["gamey", "gimpy", "gummy"] },
  { puzzleNumber: 1070, words: ["funny", "rears", "avoid", "catch"] },
  { puzzleNumber: 1069, words: ["blimp", "morin", "minty", "mined", "minus"] },
  { puzzleNumber: 1068, words: ["worth", "deals", "bevel"] },
  { puzzleNumber: 1067, words: ["brush", "click", "fifty", "digit", "titan"] },
  { puzzleNumber: 1066, words: ["stake", "drone", "chide", "glide"] },
  { puzzleNumber: 1065, words: ["highs", "shirt", "swish"] },
  { puzzleNumber: 1064, words: ["tetra", "skate", "heart", "exact", "exalt"] },
  {
    puzzleNumber: 1063,
    words: ["wonts", "manor", "bingo", "lingo", "jingo", "dingo"],
  },
  { puzzleNumber: 1062, words: ["cafes", "cover", "ricer", "dicer", "nicer"] },
  { puzzleNumber: 1061, words: ["keeps", "avoid", "icily", "witch", "hitch"] },
  { puzzleNumber: 1060, words: ["circa", "route", "trout", "tutor"] },
  { puzzleNumber: 1059, words: ["lathe", "trail", "stall"] },
  { puzzleNumber: 1058, words: ["clout", "birch", "filch", "pinch"] },
  { puzzleNumber: 1057, words: ["stone", "fails", "drags", "claws", "amass"] },
  { puzzleNumber: 1056, words: ["lithe", "peter", "doter", "otter", "outer"] },
  { puzzleNumber: 1055, words: ["punch", "ounce", "cumin"] },
  { puzzleNumber: 1054, words: ["lithe", "peter", "doter", "otter", "outer"] },
  { puzzleNumber: 1053, words: ["plate", "talon", "tidal"] },
  { puzzleNumber: 1052, words: ["drunk", "speed", "medal", "media"] },
  { puzzleNumber: 1051, words: ["imams", "plonk", "gecko", "jerky"] },
  {
    puzzleNumber: 1050,
    words: ["wizen", "tidal", "gimpy", "pivot", "pisco", "pious"],
  },
  { puzzleNumber: 1049, words: ["perks", "softy", "tasty", "misty", "musty"] },
  {
    puzzleNumber: 1048,
    words: ["hooey", "teach", "shale", "shade", "shape", "shave"],
  },
  { puzzleNumber: 1047, words: ["navel", "pedal", "decal"] },
  { puzzleNumber: 1046, words: ["blast", "dumbo", "oboes", "ebony"] },
  { puzzleNumber: 1045, words: ["fired", "spine", "smile", "slice"] },
  { puzzleNumber: 1044, words: ["money", "pithy", "girly", "risky", "diary"] },
  { puzzleNumber: 1043, words: ["milds", "whale", "glowy", "prowl"] },
  { puzzleNumber: 1042, words: ["shits", "trace", "craft"] },
  { puzzleNumber: 1041, words: ["muddy", "flout", "grubs", "prune"] },
  { puzzleNumber: 1040, words: ["watch", "smarm", "gloam", "gleam"] },
  { puzzleNumber: 1039, words: ["brink", "cited", "humid", "slaid", "vapid"] },
  { puzzleNumber: 1038, words: ["prate", "rotes", "other", "overt"] },
  { puzzleNumber: 1037, words: ["aitch", "mound", "roper", "rover"] },
  { puzzleNumber: 1036, words: ["under", "water", "layer", "laser"] },
  {
    puzzleNumber: 1035,
    words: ["stern", "laugh", "polyp", "folky", "dolly", "jolly"],
  },
  { puzzleNumber: 1034, words: ["phase", "flint", "drill", "wilds", "lucid"] },
  { puzzleNumber: 1033, words: ["stomp", "erase", "raise"] },
  { puzzleNumber: 1032, words: ["lingo", "sweat", "exact", "cadet", "facet"] },
  { puzzleNumber: 1031, words: ["fiver", "diets", "tithe"] },
  { puzzleNumber: 1030, words: ["louts", "druid", "equip"] },
  { puzzleNumber: 1029, words: ["getup", "crisp", "blimp"] },
  { puzzleNumber: 1028, words: ["lousy", "slate", "steel"] },
  { puzzleNumber: 1027, words: ["grain", "lions", "twine", "whiny"] },
  {
    puzzleNumber: 1026,
    words: ["autos", "soupy", "rouse", "house", "douse", "mouse", "louse"],
  },
  { puzzleNumber: 1025, words: ["cover", "trout", "froth", "broth"] },
  { puzzleNumber: 1024, words: ["revel", "beers", "eerie", "merge"] },
  {
    puzzleNumber: 1023,
    words: ["viola", "thrum", "ceder", "drees", "greed", "breed"],
  },
  {
    puzzleNumber: 1022,
    words: ["twill", "smile", "drily", "quilt", "child", "exile", "voila"],
  },
  {
    puzzleNumber: 1021,
    words: ["magic", "slick", "piece", "birch", "witch", "finch"],
  },
  { puzzleNumber: 1020, words: ["sicks", "blips", "geist", "wrist"] },
  { puzzleNumber: 1019, words: ["bloom", "plumb", "climb"] },
  { puzzleNumber: 1018, words: ["dream", "paths", "plant", "plait"] },
  { puzzleNumber: 1017, words: ["quoin", "upper", "truce", "rerun", "serum"] },
  { puzzleNumber: 1016, words: ["balot", "mores", "occur", "drony", "frond"] },
  { puzzleNumber: 1015, words: ["ahead", "cairn", "fault", "tasty", "taboo"] },
  { puzzleNumber: 1014, words: ["blank", "trios", "gorge", "force"] },
  { puzzleNumber: 1013, words: ["wimpy", "meant", "seams", "realm"] },
  { puzzleNumber: 1012, words: ["later", "awake", "knead", "speak"] },
  {
    puzzleNumber: 1011,
    words: ["clank", "shine", "stony", "stunt", "stuns", "stung"],
  },
  { puzzleNumber: 1010, words: ["quash", "party", "layer", "mayor"] },
  { puzzleNumber: 1009, words: ["until", "leaps", "sally"] },
  { puzzleNumber: 1008, words: ["sexed", "water", "towel"] },
  { puzzleNumber: 1007, words: ["camps", "stint", "resin", "risen"] },
  { puzzleNumber: 1006, words: ["aware", "pleat", "decay"] },
  { puzzleNumber: 1005, words: ["bleak", "teary", "shame", "shade"] },
  { puzzleNumber: 1004, words: ["forte", "pylon", "lions", "lingo"] },
  { puzzleNumber: 1003, words: ["munge", "space", "lathe", "abide"] },
  { puzzleNumber: 1002, words: ["chirp", "plane", "yelps", "spelt"] },
  { puzzleNumber: 1001, words: ["adopt", "toity", "tonic", "toxin"] },
  { puzzleNumber: 1000, words: ["funky", "crust", "erupt"] },
  { puzzleNumber: 999, words: ["prism", "silly", "sinus", "since"] },
  { puzzleNumber: 998, words: ["welts", "truss", "ratos", "ritos"] },
  { puzzleNumber: 997, words: ["fully", "level", "local"] },
  {
    puzzleNumber: 996,
    words: ["cubit", "morse", "plane", "awake", "evade", "heave"],
  },
  { puzzleNumber: 995, words: ["snark", "folks", "pesky"] },
  { puzzleNumber: 994, words: ["cheat", "plaid", "spars", "grasp"] },
  { puzzleNumber: 993, words: ["moany", "light", "heeds", "cheer"] },
  { puzzleNumber: 992, words: ["coign", "dread", "reals", "early"] },
  { puzzleNumber: 991, words: ["mirth", "plods", "blown", "clone"] },
  { puzzleNumber: 990, words: ["skips", "offer", "regal", "teary"] },
  { puzzleNumber: 989, words: ["sniff", "freed", "fetch", "flame"] },
  { puzzleNumber: 988, words: ["ploys", "snare", "skate", "state"] },
  { puzzleNumber: 987, words: ["saved", "trial", "groan", "urban"] },
  { puzzleNumber: 986, words: ["patch", "tints", "emote", "forty"] },
  { puzzleNumber: 985, words: ["tumor", "blimp", "minds", "image"] },
  { puzzleNumber: 984, words: ["boost", "plane", "lemur", "gelid", "devil"] },
  { puzzleNumber: 983, words: ["fried", "eaten", "sense"] },
  { puzzleNumber: 982, words: ["venal", "noone", "onery", "often"] },
  { puzzleNumber: 981, words: ["gauge", "costs", "sixth", "smith"] },
  {
    puzzleNumber: 980,
    words: ["storm", "rainy", "fired", "giver", "biker", "wiper", "piper"],
  },
  { puzzleNumber: 979, words: ["trial", "carat", "apart"] },
  { puzzleNumber: 978, words: ["trick", "numbs", "playa", "heavy"] },
  { puzzleNumber: 977, words: ["binds", "braid", "build"] },
  { puzzleNumber: 976, words: ["later", "patio", "maths", "match"] },
  { puzzleNumber: 975, words: ["extra", "rodeo", "peril", "price"] },
  { puzzleNumber: 974, words: ["punks", "where", "cadre", "ridge"] },
  { puzzleNumber: 973, words: ["dream", "spasm", "psalm"] },
  {
    puzzleNumber: 972,
    words: ["proxy", "stale", "stand", "staff", "stabs", "stash"],
  },
  { puzzleNumber: 971, words: ["drain", "apply", "aches", "ascot"] },
  { puzzleNumber: 970, words: ["frisk", "meant", "natch", "panty", "talon"] },
  {
    puzzleNumber: 969,
    words: ["drain", "savor", "seral", "strap", "scrag", "scram"],
  },
  { puzzleNumber: 968, words: ["tired", "blast", "stoma", "pasta"] },
  { puzzleNumber: 967, words: ["steak", "piler", "owner", "never"] },
  { puzzleNumber: 966, words: ["crypt", "drole", "bride", "fried"] },
  { puzzleNumber: 965, words: ["bloom", "exist", "sting", "stiff"] },
  { puzzleNumber: 964, words: ["final", "heals", "leaps", "place"] },
  { puzzleNumber: 963, words: ["excel", "rated", "after"] },
  { puzzleNumber: 962, words: ["mirth", "swish", "which"] },
  { puzzleNumber: 961, words: ["fours", "ready", "retch", "rerig", "repel"] },
  { puzzleNumber: 960, words: ["tines", "early", "merch", "verge"] },
  { puzzleNumber: 959, words: ["solve", "occur", "macro", "micro"] },
  { puzzleNumber: 958, words: ["snowy", "merit", "fleet", "cleft"] },
  { puzzleNumber: 957, words: ["abide", "alive"] },
  { puzzleNumber: 956, words: ["debts", "blank", "bulky"] },
  {
    puzzleNumber: 955,
    words: ["board", "might", "fluke", "spell", "repel", "expel"],
  },
  { puzzleNumber: 954, words: ["skips", "freed", "quote", "began", "leggy"] },
  { puzzleNumber: 953, words: ["waver", "plead", "beast", "snake"] },
  { puzzleNumber: 952, words: ["blast", "plead", "align", "allow", "aloof"] },
  { puzzleNumber: 951, words: ["woken", "crock", "smock", "block"] },
  { puzzleNumber: 950, words: ["queer", "rears", "relic"] },
  { puzzleNumber: 949, words: ["tread", "clout", "still"] },
  { puzzleNumber: 948, words: ["lemma", "snake", "creak", "tweak"] },
  { puzzleNumber: 947, words: ["flick", "label", "lathe", "large"] },
  { puzzleNumber: 946, words: ["reach", "ought", "thing"] },
  { puzzleNumber: 944, words: ["cloth", "troll", "stole"] },
  { puzzleNumber: 943, words: ["mouth", "tours", "court"] },
  { puzzleNumber: 942, words: ["crank", "sting", "blend", "blond"] },
  { puzzleNumber: 941, words: ["board", "piece", "munch", "lunch"] },
  { puzzleNumber: 940, words: ["today", "dough", "doing"] },
  { puzzleNumber: 939, words: ["fight", "heard"] },
  { puzzleNumber: 938, words: ["seven", "break", "route"] },
  { puzzleNumber: 937, words: ["broke", "bread", "brier", "bries", "brief"] },
  {
    puzzleNumber: 936,
    words: ["skull", "order", "ramen", "tiger", "three", "threw"],
  },
  { puzzleNumber: 935, words: ["moult", "lever", "layer", "liner"] },
  { puzzleNumber: 934, words: ["artsy", "place", "viola", "final"] },
  { puzzleNumber: 933, words: ["shirt", "stale", "stunk", "stony"] },
  { puzzleNumber: 932, words: ["shunt", "early", "baile", "cable"] },
  {
    puzzleNumber: 931,
    words: ["waver", "emote", "chide", "segue", "judge", "bulge", "lunge"],
  },
  { puzzleNumber: 930, words: ["blown", "sandy", "stank", "scant"] },
  { puzzleNumber: 929, words: ["thunk", "tryst", "tired", "twirl"] },
  { puzzleNumber: 928, words: ["sever", "monad", "blank", "fauna", "aging"] },
  { puzzleNumber: 927, words: ["plied", "loafs", "ravel", "mural"] },
  { puzzleNumber: 926, words: ["witch", "tears", "stoat", "sault", "salty"] },
  { puzzleNumber: 925, words: ["cloth", "third", "three"] },
  { puzzleNumber: 924, words: ["whelp", "child"] },
  { puzzleNumber: 922, words: ["shalt", "clade", "leary", "learn"] },
  {
    puzzleNumber: 921,
    words: ["which", "brink", "toils", "spied", "daisy"],
  },
  { puzzleNumber: 920, words: ["fauna", "stonk", "prong", "phone"] },
  {
    puzzleNumber: 919,
    words: ["hardy", "boils", "canoe", "outie", "elope", "evoke"],
  },
  {
    puzzleNumber: 918,
    words: ["hides", "pleat", "beany", "frame", "crave", "grace"],
  },
  { puzzleNumber: 917, words: ["gripe", "scope", "slope"] },
  { puzzleNumber: 916, words: ["hoops", "mocha", "touch"] },
  { puzzleNumber: 915, words: ["warps", "snail", "stall", "small"] },
  { puzzleNumber: 914, words: ["spurt", "tamed", "table"] },
  { puzzleNumber: 912, words: ["angst", "mince", "donor", "bunny", "funny"] },
  {
    puzzleNumber: 911,
    words: ["hawks", "badge", "banal", "baron", "baton", "bacon"],
  },
  { puzzleNumber: 910, words: ["blows", "globe"] },
  {
    puzzleNumber: 909,
    words: ["harks", "beige", "ditto", "tonic", "toxic", "topic"],
  },
  { puzzleNumber: 908, words: ["crans", "quiet", "would"] },
  { puzzleNumber: 907, words: ["eisel", "sends", "snore", "stean", "spent"] },
  { puzzleNumber: 906, words: ["acute", "store", "istle", "these"] },
  { puzzleNumber: 905, words: ["stars", "mushy", "plush", "house"] },
  { puzzleNumber: 904, words: ["wants", "knack", "chain"] },
  { puzzleNumber: 903, words: ["snexus", "stark", "shard", "sharp"] },
  { puzzleNumber: 902, words: ["table", "linen", "repel", "sleep"] },
  { puzzleNumber: 900, words: ["liked", "worst", "woman"] },
  { puzzleNumber: 899, words: ["loose", "worth", "mound", "young"] },
  { puzzleNumber: 898, words: ["scars", "plate", "adapt"] },
  { puzzleNumber: 897, words: ["fluke", "sense", "genie", "genre"] },
  { puzzleNumber: 896, words: ["bench", "enter", "toned", "taken"] },
  { puzzleNumber: 895, words: ["panic", "until", "resin"] },
  { puzzleNumber: 894, words: ["tight", "mochi", "sushi"] },
  { puzzleNumber: 891, words: ["churl", "scene", "scope"] },
  { puzzleNumber: 890, words: ["wharf", "sweat", "trawl", "tawny"] },
  { puzzleNumber: 889, words: ["glass", "grime", "guide"] },
  { puzzleNumber: 888, words: ["butty", "thigh", "thorn", "throw"] },
  {
    puzzleNumber: 887,
    words: ["hefts", "evade", "creep", "gleek", "uneeq", "queen"],
  },
  { puzzleNumber: 886, words: ["hafts", "wordy", "bleep", "cupel", "pixel"] },
  { puzzleNumber: 885, words: ["bough", "dross", "ocean", "paino"] },
  { puzzleNumber: 884, words: ["crank", "canon", "canal", "canes", "candy"] },
  { puzzleNumber: 883, words: ["games", "crone", "elude", "quete", "queue"] },
  { puzzleNumber: 882, words: ["zebra", "doily", "chins", "thing", "think"] },
  { puzzleNumber: 881, words: ["cysts", "turfy", "tarry", "tardy"] },
  { puzzleNumber: 880, words: ["again", "slept", "frost", "crust", "trust"] },
  {
    puzzleNumber: 879,
    words: ["loins", "sired", "sissy", "situp", "sixth", "sight"],
  },
  {
    puzzleNumber: 878,
    words: ["budge", "roils", "stack", "savvy", "sappy", "sassy"],
  },
  { puzzleNumber: 877, words: ["leant", "snide", "green"] },
  { puzzleNumber: 876, words: ["alive", "arson", "abhor", "actor"] },
  { puzzleNumber: 875, words: ["grime", "essay", "seats", "leash"] },
  { puzzleNumber: 874, words: ["dippy", "hills", "finer", "ninja"] },
  { puzzleNumber: 868, words: ["sweat", "palet", "terai", "trace", "trade"] },
  { puzzleNumber: 867, words: ["water", "vapid", "magic", "mafia", "mania"] },
  {
    puzzleNumber: 866,
    words: ["foggy", "occur", "valor", "abhor", "armor", "ardor"],
  },
  { puzzleNumber: 865, words: ["whine", "tints", "intro", "until"] },
  {
    puzzleNumber: 864,
    words: ["chirr", "fowls", "leave", "panel", "equal", "bleat"],
  },
  { puzzleNumber: 863, words: ["chuff", "growl", "grill", "grail"] },
  { puzzleNumber: 862, words: ["chins", "thong", "phone", "phony"] },
  { puzzleNumber: 861, words: ["ships", "musty", "maser", "mason"] },
  { puzzleNumber: 860, words: ["lined", "alone", "noble"] },
  {
    puzzleNumber: 859,
    words: ["salad", "begin", "fiery", "rivet", "winge", "niche", "pique"],
  },
  { puzzleNumber: 858, words: ["snore", "heart", "petri", "retry"] },
  { puzzleNumber: 857, words: ["still", "rouse", "cause"] },
  {
    puzzleNumber: 856,
    words: ["minds", "nicer", "wizen", "vixen", "liven", "given"],
  },
  { puzzleNumber: 855, words: ["smack", "smirk"] },
  { puzzleNumber: 854, words: ["stack", "chore", "occur"] },
  { puzzleNumber: 853, words: ["trail", "splat"] },
  { puzzleNumber: 852, words: ["teach", "mercy"] },
  { puzzleNumber: 849, words: ["chose", "graph"] },
  {
    puzzleNumber: 848,
    words: ["smith", "creed", "alone", "mealy", "leafy", "leaky"],
  },
  { puzzleNumber: 847, words: ["queen", "knelt", "scent", "agent"] },
  { puzzleNumber: 846, words: ["learn", "knelt", "ingle", "uncle"] },
  { puzzleNumber: 845, words: ["koans", "kneel", "knell", "knelt"] },
  {
    puzzleNumber: 844,
    words: ["grasp", "scone", "stint", "sunny", "shuns", "skunk"],
  },
  { puzzleNumber: 843, words: ["worry", "seeds", "snail"] },
  { puzzleNumber: 842, words: ["eight", "froth", "wrath", "truth"] },
  { puzzleNumber: 841, words: ["wreak", "emote", "niche", "since", "binge"] },
  { puzzleNumber: 840, words: ["plugs", "molar", "labor", "atoll", "viola"] },
  { puzzleNumber: 839, words: ["spicy", "cried", "chime"] },
  { puzzleNumber: 838, words: ["fresh", "lunch", "bunch"] },
  { puzzleNumber: 837, words: ["wound", "acute", "spurt"] },
  { puzzleNumber: 836, words: ["mints", "ideal", "felix", "slice", "while"] },
  {
    puzzleNumber: 835,
    words: ["troth", "range", "piers", "berry", "ferry", "merry"],
  },
  { puzzleNumber: 834, words: ["bathe", "beets", "beget", "beret"] },
  {
    puzzleNumber: 833,
    words: ["outta", "apple", "marsh", "nanny", "caddy", "daddy"],
  },
  { puzzleNumber: 832, words: ["pocks", "could", "comby", "cover", "cocoa"] },
  { puzzleNumber: 831, words: ["leave", "lambs", "lilac", "local", "loyal"] },
  { puzzleNumber: 830, words: ["pours", "crowd", "carol"] },
  { puzzleNumber: 829, words: ["rainy", "gowns", "stone"] },
  { puzzleNumber: 828, words: ["still", "lunar", "polar", "clear"] },
  { puzzleNumber: 827, words: ["worry", "occur", "older"] },
  { puzzleNumber: 826, words: ["white", "skate", "route", "quote"] },
  { puzzleNumber: 825, words: ["years", "dolly", "lefty", "lumpy", "lucky"] },
  { puzzleNumber: 824, words: ["snows", "corse", "rouse"] },
  { puzzleNumber: 823, words: ["trunk", "poise", "bleed", "ideal", "dwell"] },
  { puzzleNumber: 822, words: ["ought", "sighs", "ghast", "gnash"] },
  { puzzleNumber: 821, words: ["ether", "brash", "birch"] },
  { puzzleNumber: 820, words: ["lungs", "bogey", "grimy", "giddy"] },
  {
    puzzleNumber: 819,
    words: ["query", "midst", "flail", "which", "boing", "onion"],
  },
  { puzzleNumber: 818, words: ["amaze", "plate", "scape", "space"] },
  { puzzleNumber: 817, words: ["pupil", "vined", "bride"] },
  { puzzleNumber: 801, words: ["story", "creed", "carer", "caper"] },
  { puzzleNumber: 800, words: ["based", "enter", "tripe", "write"] },
  { puzzleNumber: 799, words: ["shout", "pence", "peace"] },
  { puzzleNumber: 798, words: ["moody", "prone", "abort", "scour", "choir"] },
  { puzzleNumber: 797, words: ["habit", "plage", "cream", "ocean"] },
  { puzzleNumber: 796, words: ["prude", "cards", "wordy"] },
  { puzzleNumber: 795, words: ["weird", "feral", "merge", "verve"] },
  { puzzleNumber: 794, words: ["erupt", "penis", "spice"] },
  { puzzleNumber: 793, words: ["buyer", "beads", "beach"] },
  { puzzleNumber: 792, words: ["esses", "space", "wrest", "blest", "quest"] },
  {
    puzzleNumber: 791,
    words: ["leech", "moans", "madly", "marts", "magic", "magma"],
  },
  { puzzleNumber: 790, words: ["bambi", "float", "react", "exact"] },
  {
    puzzleNumber: 789,
    words: ["needs", "boils", "grits", "chips", "swiss", "amiss"],
  },
  { puzzleNumber: 788, words: ["stuck", "scour", "scrub"] },
  { puzzleNumber: 787, words: ["demur", "slide", "fiend", "inked", "index"] },
  { puzzleNumber: 786, words: ["polyp", "ready", "flaky", "snaky"] },
  { puzzleNumber: 785, words: ["since", "throw", "wrath"] },
  { puzzleNumber: 784, words: ["until", "quick"] },
  { puzzleNumber: 782, words: ["world", "scene", "pipet", "empty"] },
  { puzzleNumber: 781, words: ["tried", "cheer", "loner", "lover"] },
  {
    puzzleNumber: 780,
    words: ["conch", "radar", "fluff", "vulva", "gully", "bully"],
  },
  { puzzleNumber: 779, words: ["doors", "groom", "troop", "croon", "brook"] },
  { puzzleNumber: 778, words: ["video", "sonar", "folly", "polyp"] },
  { puzzleNumber: 777, words: ["ample", "arose", "atone", "anode"] },
  { puzzleNumber: 776, words: ["other", "third", "shart", "chart"] },
  { puzzleNumber: 775, words: ["forum", "parry", "party"] },
  { puzzleNumber: 774, words: ["niche", "strep", "valet", "beget"] },
  { puzzleNumber: 773, words: ["culch", "graph", "teeth", "tenth"] },
  { puzzleNumber: 772, words: ["wield", "scale", "stole", "styfe"] },
  { puzzleNumber: 771, words: ["magic", "baths", "bathe"] },
  { puzzleNumber: 770, words: ["relax", "lurid", "curly"] },
  { puzzleNumber: 769, words: ["modus", "ottos", "ethos"] },
  { puzzleNumber: 768, words: ["rebel", "point", "misos", "disco"] },
  { puzzleNumber: 767, words: ["pause", "weald", "meant", "react", "heart"] },
  { puzzleNumber: 766, words: ["legal", "cruel", "novel", "spiel", "wheel"] },
  { puzzleNumber: 765, words: ["court", "poled", "bongo", "wombs", "hobby"] },
  { puzzleNumber: 764, words: ["lance", "glade", "shale", "whale"] },
  { puzzleNumber: 763, words: ["which", "frogs", "froze"] },
  { puzzleNumber: 762, words: ["hobby", "bandy", "bigly", "burly"] },
  { puzzleNumber: 761, words: ["spoil", "bugle", "clank", "flank"] },
  { puzzleNumber: 760, words: ["verse", "chuck", "bacon", "tonic"] },
  { puzzleNumber: 759, words: ["dingo", "crest", "payer", "buyer", "flyer"] },
  { puzzleNumber: 758, words: ["doubt", "demon", "dinos", "droop"] },
  { puzzleNumber: 757, words: ["quest", "patio", "topaz"] },
  { puzzleNumber: 756, words: ["thigh", "prose", "drole", "crone"] },
  { puzzleNumber: 755, words: ["taxed", "blend", "fiend"] },
  { puzzleNumber: 754, words: ["event", "slake", "farce", "barge"] },
  { puzzleNumber: 753, words: ["usual", "towel", "whirl"] },
  { puzzleNumber: 752, words: ["reuse", "error", "egret", "earth"] },
  {
    puzzleNumber: 751,
    words: ["broke", "colas", "goldy", "holly", "jolly", "folly"],
  },
  { puzzleNumber: 750, words: ["mites", "rated", "noter", "enter"] },
  { puzzleNumber: 749, words: ["verse", "dream", "riper", "lower", "cower"] },
  { puzzleNumber: 746, words: ["major", "filed", "diddy", "windy"] },
  { puzzleNumber: 745, words: ["chink", "lanes", "tenor", "venom"] },
  { puzzleNumber: 744, words: ["being", "avert", "stoke", "toled", "hotel"] },
  {
    puzzleNumber: 743,
    words: ["total", "dodge", "bombs", "mousy", "mopsy", "mossy"],
  },
  { puzzleNumber: 742, words: ["being", "bored", "bases", "bleep"] },
  { puzzleNumber: 741, words: ["pored", "girls", "surfy", "straw"] },
  { puzzleNumber: 740, words: ["spend", "denim", "diner"] },
  { puzzleNumber: 739, words: ["foxes", "birch", "react", "tract"] },
  { puzzleNumber: 738, words: ["morel", "gloat", "about"] },
  { puzzleNumber: 737, words: ["known", "gists", "ghast", "geest", "guest"] },
  { puzzleNumber: 736, words: ["gelid", "fades", "ruder", "rodeo"] },
  { puzzleNumber: 735, words: ["prior", "dread", "brand", "grand"] },
  { puzzleNumber: 734, words: ["offer", "doted", "towel", "comet", "covet"] },
  {
    puzzleNumber: 733,
    words: ["block", "fugue", "waste", "paste", "haste", "taste"],
  },
  { puzzleNumber: 732, words: ["small", "wrack", "crate", "crane"] },
  { puzzleNumber: 731, words: ["vague", "crock", "troop", "droit", "frost"] },
  { puzzleNumber: 730, words: ["jetty", "lunch", "braid", "among", "kazoo"] },
  { puzzleNumber: 729, words: ["warps", "snoot", "shell", "shyly"] },
  { puzzleNumber: 728, words: ["vocal", "crass", "acrid", "ranch"] },
  { puzzleNumber: 727, words: ["visor", "rates", "start", "strap"] },
  { puzzleNumber: 726, words: ["trope", "lunge", "sieve", "cache", "maybe"] },
  { puzzleNumber: 725, words: ["found", "great", "price", "crime"] },
  { puzzleNumber: 724, words: ["doing", "leant", "clunk", "slunk", "plunk"] },
  { puzzleNumber: 723, words: ["busts", "gnarr", "prong", "wrong"] },
  { puzzleNumber: 722, words: ["human", "baron", "twain", "plain", "again"] },
  { puzzleNumber: 721, words: ["whose", "crash", "salsa", "balsa"] },
  { puzzleNumber: 720, words: ["raise", "porch", "torch", "lurch", "crumb"] },
  { puzzleNumber: 719, words: ["pitch", "lathe", "hater"] },
  { puzzleNumber: 718, words: ["aorta", "melds", "fugue", "ennui"] },
  { puzzleNumber: 715, words: ["bulky", "brand", "beats", "beast"] },
  { puzzleNumber: 714, words: ["veldt", "chunk", "irony", "fanny", "nanny"] },
  { puzzleNumber: 713, words: ["hoary", "heeds", "humid"] },
  {
    puzzleNumber: 712,
    words: ["point", "barfy", "mashy", "daddy", "gauzy", "jazzy"],
  },
  { puzzleNumber: 711, words: ["elide", "smile", "guile", "agile"] },
  { puzzleNumber: 710, words: ["quirt", "shoes", "panel", "kneel"] },
  { puzzleNumber: 709, words: ["fight", "clove", "dorse", "mouse"] },
  { puzzleNumber: 708, words: ["skips", "brunt", "bleed", "bagel"] },
  {
    puzzleNumber: 707,
    words: ["queue", "fizzy", "droid", "iotas", "inbox", "igloo"],
  },
  { puzzleNumber: 706, words: ["steak", "basis", "brash"] },
  { puzzleNumber: 700, words: ["creep", "night", "flays", "flask"] },
  { puzzleNumber: 698, words: ["grift", "adore", "scorn", "sworn", "shorn"] },
  { puzzleNumber: 697, words: ["miser", "tough", "pally", "plaza", "plank"] },
  { puzzleNumber: 696, words: ["sprog", "field", "unlet", "metal", "latte"] },
  { puzzleNumber: 695, words: ["bagel", "taste", "paire", "mauve", "canoe"] },
  { puzzleNumber: 694, words: ["yield", "frogs", "scarf"] },
  { puzzleNumber: 693, words: ["scree", "acron", "acrid"] },
  { puzzleNumber: 692, words: ["proto", "niche", "chunk", "snack"] },
  { puzzleNumber: 691, words: ["waits", "round", "chore", "grovy", "broom"] },
  { puzzleNumber: 690, words: ["chart", "ethic"] },
  { puzzleNumber: 689, words: ["treat", "ahold", "wacko", "socia", "cocoa"] },
  { puzzleNumber: 688, words: ["plank", "balot", "agloo", "aglow"] },
  { puzzleNumber: 687, words: ["north", "macho", "helos", "ahold", "ghoul"] },
  { puzzleNumber: 686, words: ["testy", "place", "added", "anger"] },
  {
    puzzleNumber: 685,
    words: ["fubar", "broke", "boney", "begot", "bebop", "below"],
  },
  { puzzleNumber: 684, words: ["tenor", "plaid", "puffy", "guppy"] },
  { puzzleNumber: 683, words: ["avert", "prune", "ridge", "dorse", "horde"] },
  { puzzleNumber: 682, words: ["skips", "stank", "smoke", "sulky"] },
  { puzzleNumber: 680, words: ["inter", "dough", "sappy", "plack", "plaza"] },
  { puzzleNumber: 679, words: ["dream", "redan", "cedar"] },
  { puzzleNumber: 678, words: ["crowd", "cater", "cigar", "circa"] },
  { puzzleNumber: 677, words: ["bilge", "guilt", "igloo", "logic"] },
  { puzzleNumber: 676, words: ["tears", "petri", "metro"] },
  {
    puzzleNumber: 675,
    words: ["deign", "erase", "morel", "voter", "power", "joker"],
  },
  { puzzleNumber: 674, words: ["decaf", "drips", "dilly", "dight", "ditto"] },
  { puzzleNumber: 673, words: ["boast", "liked", "fungi", "unity", "unzip"] },
  {
    puzzleNumber: 672,
    words: ["livid", "fresh", "error", "crone", "trope", "broke"],
  },
  { puzzleNumber: 671, words: ["would", "skips", "hacky", "kayak"] },
  { puzzleNumber: 670, words: ["bundt", "trick", "atoll", "lasts", "plate"] },
  { puzzleNumber: 669, words: ["press", "apply", "chimp", "thump"] },
  { puzzleNumber: 668, words: ["grass", "flown", "notch", "honey", "hound"] },
  { puzzleNumber: 667, words: ["stiff", "cliff", "griff", "whiff"] },
  { puzzleNumber: 666, words: ["games", "blend", "dwell", "dwelt"] },
  { puzzleNumber: 665, words: ["brine", "stung", "gland", "agony"] },
  { puzzleNumber: 664, words: ["rerun", "piped", "fries", "thief"] },
  { puzzleNumber: 662, words: ["bones", "board", "boral", "borax"] },
  { puzzleNumber: 661, words: ["style", "qualm"] },
  { puzzleNumber: 657, words: ["swear", "diner", "nuder", "under"] },
  { puzzleNumber: 656, words: ["power", "elect", "leave", "leans", "leafy"] },
  { puzzleNumber: 655, words: ["moors", "small", "smash"] },
  { puzzleNumber: 654, words: ["primp", "rider", "ratio"] },
  { puzzleNumber: 653, words: ["inter", "proud", "rooks", "glory", "flora"] },
  { puzzleNumber: 652, words: ["suede", "sonar", "stool", "stows", "stock"] },
  { puzzleNumber: 651, words: ["train", "polar", "razes", "march"] },
  { puzzleNumber: 648, words: ["preps", "stole", "asset", "inset", "beset"] },
  {
    puzzleNumber: 644,
    words: ["visit", "glade", "frown", "purry", "curry", "hurry"],
  },
  { puzzleNumber: 643, words: ["train", "crust", "grout"] },
  { puzzleNumber: 642, words: ["slang", "staid"] },
  { puzzleNumber: 641, words: ["group", "quilt", "bundt", "duvet"] },
  { puzzleNumber: 640, words: ["revel", "sacks", "downy", "tough"] },
  { puzzleNumber: 639, words: ["paint", "frogs", "glove"] },
  { puzzleNumber: 638, words: ["stole", "owned", "defog", "credo"] },
  { puzzleNumber: 637, words: ["bored", "stuck", "catty", "yacht"] },
  { puzzleNumber: 636, words: ["video", "fresh", "table", "mealy"] },
  { puzzleNumber: 635, words: ["bloop", "crude", "cedar", "cider"] },
  { puzzleNumber: 634, words: ["evens", "yeesh", "sleet", "sweep"] },
  { puzzleNumber: 633, words: ["ghast", "poops", "surly"] },
  { puzzleNumber: 632, words: ["disco", "plane", "flame", "blame"] },
  { puzzleNumber: 631, words: ["woops", "death", "mirth", "girth", "birth"] },
  { puzzleNumber: 629, words: ["would", "later", "riles", "repel", "revel"] },
  { puzzleNumber: 628, words: ["maven", "slice", "probe", "there", "where"] },
  { puzzleNumber: 627, words: ["bough", "angle", "regal"] },
  { puzzleNumber: 626, words: ["bread", "score", "horse"] },
  { puzzleNumber: 625, words: ["right", "pines", "pinny", "pinky"] },
  {
    puzzleNumber: 624,
    words: ["cafes", "block", "occur", "tonic", "topic", "toxic"],
  },
  { puzzleNumber: 623, words: ["plant", "trine", "trend"] },
  {
    puzzleNumber: 622,
    words: ["crook", "blame", "pains", "assay", "squad", "squat"],
  },
  { puzzleNumber: 621, words: ["stoic", "broke", "abode", "above"] },
  { puzzleNumber: 618, words: ["delay", "emote", "biome", "moose"] },
  { puzzleNumber: 617, words: ["going", "rowed", "bouts", "cooky", "polka"] },
  { puzzleNumber: 616, words: ["robot", "corgi", "pored", "worse"] },
  { puzzleNumber: 615, words: ["meter", "ruins", "spurt", "syrup"] },
  { puzzleNumber: 614, words: ["boots", "wrath", "petty", "nifty", "fifty"] },
  { puzzleNumber: 613, words: ["shard", "array", "arbor"] },
  { puzzleNumber: 612, words: ["about", "malus", "vague"] },
  {
    puzzleNumber: 611,
    words: ["tarry", "error", "refer", "rider", "river", "riser", "riper"],
  },
  {
    puzzleNumber: 610,
    words: ["whole", "bunny", "puffy", "sucky", "dummy", "ruddy"],
  },
  {
    puzzleNumber: 609,
    words: ["tacos", "shone", "moose", "gloss", "dross", "kiosk"],
  },
  { puzzleNumber: 608, words: ["fully", "latch", "altar", "avail"] },
  { puzzleNumber: 607, words: ["algae", "brave", "taste", "cache"] },
  { puzzleNumber: 606, words: ["salty", "dared", "manic", "magic"] },
  { puzzleNumber: 605, words: ["fiber", "plant", "lacks", "sally", "salsa"] },
  { puzzleNumber: 604, words: ["brink", "thong", "mound", "pound", "sound"] },
  { puzzleNumber: 603, words: ["tummy", "round", "laugh", "usage"] },
  { puzzleNumber: 602, words: ["baggy", "grail", "giant"] },
  {
    puzzleNumber: 601,
    words: ["tired", "deeps", "death", "delve", "defog", "debug"],
  },
  {
    puzzleNumber: 600,
    words: ["tango", "place", "deads", "ready", "beady", "heady"],
  },
  { puzzleNumber: 599, words: ["scowl", "shear", "sated", "stage"] },
  { puzzleNumber: 598, words: ["elbow", "glitz", "plaid", "flair"] },
  { puzzleNumber: 597, words: ["crate", "abode", "apple"] },
  { puzzleNumber: 596, words: ["wrong", "sneak", "punty", "linty", "ninth"] },
  { puzzleNumber: 595, words: ["cargo", "batch", "fancy", "dance"] },
  {
    puzzleNumber: 594,
    words: ["scour", "whump", "guide", "unity", "until", "unlit"],
  },
  {
    puzzleNumber: 593,
    words: ["under", "chill", "smoky", "gassy", "pasty", "tasty"],
  },
  { puzzleNumber: 592, words: ["sicks", "scalp", "scold"] },
  { puzzleNumber: 591, words: ["gulps", "fares", "stirs", "cross"] },
  { puzzleNumber: 590, words: ["boxer", "drive", "grave", "crave"] },
  { puzzleNumber: 589, words: ["stall", "guise", "winos", "dishy", "fishy"] },
  { puzzleNumber: 588, words: ["worse", "guard", "churn", "flirt"] },
  { puzzleNumber: 587, words: ["rifts", "array", "lorry", "worry"] },
  {
    puzzleNumber: 586,
    words: ["jazzy", "gurdy", "whiny", "peppy", "felty", "beefy"],
  },
  { puzzleNumber: 585, words: ["minor", "mails", "maize"] },
  { puzzleNumber: 584, words: ["proud", "touts", "count"] },
  { puzzleNumber: 583, words: ["sleep", "elate", "elope", "elude"] },
  { puzzleNumber: 582, words: ["bosun", "grimy", "meany", "mazey", "matey"] },
  { puzzleNumber: 581, words: ["float", "glide", "plumb", "blurb"] },
  { puzzleNumber: 580, words: ["repel", "ulcer", "alter"] },
  { puzzleNumber: 578, words: ["brits", "rodeo", "chard"] },
  { puzzleNumber: 577, words: ["build", "apode", "adopt"] },
  { puzzleNumber: 576, words: ["maths", "groin", "drove", "frock"] },
  { puzzleNumber: 575, words: ["flows", "sneer", "spire"] },
  { puzzleNumber: 574, words: ["hinge", "droop", "vocal", "loams", "koala"] },
  { puzzleNumber: 573, words: ["kempt", "lambs", "woman", "adman", "human"] },
  { puzzleNumber: 571, words: ["anime", "eager", "peats", "leapt"] },
  { puzzleNumber: 570, words: ["scant", "sneak", "sedan"] },
  { puzzleNumber: 569, words: ["tired", "piece", "pixie"] },
  { puzzleNumber: 568, words: ["sorry", "adore", "opera"] },
  { puzzleNumber: 567, words: ["sword", "ponce", "ovine", "melon", "lemon"] },
  { puzzleNumber: 566, words: ["scrat", "guild", "libel", "belie"] },
  { puzzleNumber: 565, words: ["awake", "keeps", "sleek"] },
  { puzzleNumber: 564, words: ["offal", "layed", "layer"] },
  { puzzleNumber: 563, words: ["clink", "niche", "panic", "antic"] },
  { puzzleNumber: 562, words: ["train", "first", "shirt", "skirt"] },
  { puzzleNumber: 561, words: ["klutz", "drive", "swine", "whine"] },
  { puzzleNumber: 560, words: ["haste", "valor", "gaily", "wally", "manly"] },
  { puzzleNumber: 559, words: ["knave", "iotas", "polar", "molar"] },
  { puzzleNumber: 556, words: ["tower", "dough", "foods", "mondo", "condo"] },
  {
    puzzleNumber: 555,
    words: ["poops", "frack", "delve", "midge", "nudge", "budge", "judge"],
  },
  {
    puzzleNumber: 554,
    words: ["groom", "chart", "intra", "sutra", "tetra", "extra"],
  },
  { puzzleNumber: 553, words: ["power", "podge", "posse", "poise"] },
  {
    puzzleNumber: 552,
    words: ["gouge", "dorky", "coral", "forma", "sorta", "porta", "iorta"],
  },
  { puzzleNumber: 551, words: ["mason", "fried", "bevel", "wheel", "excel"] },
  { puzzleNumber: 550, words: ["hoist", "crude", "furry", "augur", "lunar"] },
  { puzzleNumber: 549, words: ["winch", "heigh", "shirk", "third"] },
  {
    puzzleNumber: 545,
    words: ["focus", "avoid", "growl", "tromp", "prone", "probe"],
  },
  { puzzleNumber: 544, words: ["hotel", "drill", "rival"] },
  { puzzleNumber: 543, words: ["chomp", "grade", "lunas", "usual"] },
  { puzzleNumber: 542, words: ["nerve", "badge", "slice", "smote", "spoke"] },
  { puzzleNumber: 541, words: ["knell", "scalp", "apply"] },
  { puzzleNumber: 540, words: ["grand", "lanes", "eaten", "naive"] },
  { puzzleNumber: 539, words: ["piano", "donor", "flown", "snobs", "knock"] },
  { puzzleNumber: 538, words: ["learn", "roars", "fraud", "braid"] },
  { puzzleNumber: 537, words: ["focus", "after", "infer"] },
  { puzzleNumber: 536, words: ["train", "emote", "gothy", "doubt", "joust"] },
  { puzzleNumber: 535, words: ["dross", "blurt", "rebar", "caber", "amber"] },
  { puzzleNumber: 534, words: ["blink", "knots", "wonky", "woken"] },
  { puzzleNumber: 533, words: ["snowy", "float", "abode", "adore"] },
  { puzzleNumber: 532, words: ["droop", "torso"] },
  { puzzleNumber: 531, words: ["clogs", "chart", "champ", "chafe"] },
  { puzzleNumber: 530, words: ["phage", "error", "ennui", "elect", "eject"] },
  {
    puzzleNumber: 529,
    words: ["trash", "stoop", "stuck", "stung", "stuff", "studs", "study"],
  },
  { puzzleNumber: 528, words: ["wreck", "feint", "boned", "nudes", "undue"] },
  { puzzleNumber: 527, words: ["break", "depth", "tepid"] },
  { puzzleNumber: 526, words: ["chaos", "alpha", "happy"] },
  { puzzleNumber: 525, words: ["alloy", "blade", "pleat", "clear", "clean"] },
  { puzzleNumber: 524, words: ["faked", "blows", "unity", "pithy", "itchy"] },
  { puzzleNumber: 523, words: ["feast"] },
  { puzzleNumber: 522, words: ["lunge", "chore", "arise", "tribe", "drive"] },
  {
    puzzleNumber: 521,
    words: ["buggy", "fixed", "snipe", "prize", "price", "prime"],
  },
  { puzzleNumber: 520, words: ["couch", "groan", "ovals", "patio", "axiom"] },
  { puzzleNumber: 519, words: ["today", "walks", "crazy", "brave"] },
  {
    puzzleNumber: 518,
    words: ["eerie", "creed", "shear", "opera", "alert", "avert"],
  },
  { puzzleNumber: 517, words: ["skill", "blade", "clout", "glyph"] },
  { puzzleNumber: 516, words: ["wield", "scene", "there"] },
  {
    puzzleNumber: 515,
    words: ["froze", "reels", "tired", "waver", "caper", "maker", "baker"],
  },
  { puzzleNumber: 514, words: ["bogey", "crush", "stark", "snarl"] },
  { puzzleNumber: 513, words: ["month", "murky", "maple"] },
  { puzzleNumber: 512, words: ["brunt", "plank", "deans", "inane"] },
  { puzzleNumber: 511, words: ["chain", "break", "maple", "valet"] },
  { puzzleNumber: 510, words: ["vegan", "pedal", "medal"] },
  { puzzleNumber: 509, words: ["color", "shift", "taiga", "unite"] },
  { puzzleNumber: 508, words: ["jazzy", "lanky", "nappy", "rainy"] },
  { puzzleNumber: 507, words: ["frock", "thine", "gales", "swell", "spell"] },
  { puzzleNumber: 506, words: ["botch", "biker", "beige", "begin"] },
  { puzzleNumber: 505, words: ["dream", "angel", "leash", "scale", "stale"] },
  { puzzleNumber: 504, words: ["again", "drape", "dread", "dream"] },
  { puzzleNumber: 503, words: ["frown", "chomp", "photo"] },
  { puzzleNumber: 502, words: ["knife", "growl", "sloth", "blood", "aloud"] },
  { puzzleNumber: 501, words: ["spoon", "plant", "inept"] },
  {
    puzzleNumber: 500,
    words: ["onion", "night", "pinch", "pined", "pines", "piney"],
  },
  { puzzleNumber: 499, words: ["hyped", "porky", "spicy", "aptly"] },
  { puzzleNumber: 498, words: ["every", "laugh", "waltz"] },
  { puzzleNumber: 497, words: ["fight", "diode", "riven", "piles", "libel"] },
  { puzzleNumber: 496, words: ["crash", "sauna", "sedan", "sneak"] },
  { puzzleNumber: 495, words: ["storm", "quark", "faire", "carry"] },
  {
    puzzleNumber: 494,
    words: ["grief", "folds", "flown", "flock", "float", "flout"],
  },
  { puzzleNumber: 493, words: ["cloth", "roads", "women", "boggy", "foggy"] },
  { puzzleNumber: 492, words: ["porch", "built", "adult", "fault"] },
  { puzzleNumber: 491, words: ["spank", "butte", "guild", "humor", "mummy"] },
  { puzzleNumber: 490, words: ["later", "dowel", "spiel"] },
  { puzzleNumber: 489, words: ["fluff", "adopt", "crone", "grove"] },
  { puzzleNumber: 488, words: ["haunt", "noise", "pined", "denim"] },
  {
    puzzleNumber: 487,
    words: ["allay", "tooth", "verve", "rigid", "primp", "quirk"],
  },
  {
    puzzleNumber: 486,
    words: ["foggy", "quell", "strep", "dents", "exist"],
  },
  { puzzleNumber: 485, words: ["doing", "fines", "skein", "stein"] },
  { puzzleNumber: 484, words: ["ditzy", "words", "spade"] },
  { puzzleNumber: 483, words: ["gorge", "sunny", "cliff", "catch"] },
  { puzzleNumber: 482, words: ["mound", "ovary", "grope", "riots", "floor"] },
  { puzzleNumber: 480, words: ["clued", "aback", "mimic", "ionic"] },
  { puzzleNumber: 479, words: ["clots", "ralph", "dally", "valid"] },
];
export const poems = [
  /*
  picky teeth snarl growl drool
  chili lemon salty salad salsa
  bliss honor truth credo grace
  nutty silly goofy wacky crazy
  */

  { puzzleNumber: 29, words: ["syrup", "jelly", "gummy", "candy", "taffy"] },
  { puzzleNumber: 28, words: ["check", "proof", "tally", "audit", "digit"] },
  { puzzleNumber: 27, words: ["sooth", "murky", "relax", "blare"] },
  { puzzleNumber: 26, words: ["mucus", "nosey", "sniff", "snort", "snarl"] },
  { puzzleNumber: 25, words: ["winch", "turbo", "evoke", "adopt", "flood"] },
  { puzzleNumber: 24, words: ["decor", "panel", "shape", "frame", "image"] },
  { puzzleNumber: 23, words: ["curve", "round", "whirl", "twirl", "swirl"] },
  { puzzleNumber: 22, words: ["happy", "merry", "jolly", "giddy", "sunny"] },
  { puzzleNumber: 21, words: ["legal", "theft", "prove", "crime", "bribe"] },
  { puzzleNumber: 20, words: ["error", "shame", "lapse", "cause"] },
  { puzzleNumber: 19, words: ["mucus", "nosey", "sniff", "snort", "snarl"] },
  { puzzleNumber: 18, words: ["vocal", "opera", "radio", "audio"] },
  { puzzleNumber: 17, words: ["audit", "clock", "proof", "probe", "prove"] },
  { puzzleNumber: 16, words: ["mouth", "pique", "sulky", "surly"] },
  { puzzleNumber: 15, words: ["savvy", "brain", "guard", "aware", "alarm"] },
  { puzzleNumber: 14, words: ["juicy", "mango"] },
  { puzzleNumber: 13, words: ["fruit", "cacao", "vodka", "lemon", "spoon"] },
  { puzzleNumber: 12, words: ["jelly", "glaze", "cream", "treat"] },
  { puzzleNumber: 11, words: ["motor", "alarm", "drive", "break", "wreck"] },
  { puzzleNumber: 10, words: ["buyer", "merit", "price", "prize"] },
  { puzzleNumber: 9, words: ["spell", "funny", "magic", "trick", "witch"] },
  { puzzleNumber: 8, words: ["bless", "mercy", "grace"] },
  { puzzleNumber: 7, words: ["pitch", "lyric", "scale", "clear", "vocal"] },
  { puzzleNumber: 6, words: ["shore", "creek", "river", "water"] },
  { puzzleNumber: 5, words: ["scrub", "rinse", "brush", "trash"] },
  { puzzleNumber: 4, words: ["rusty", "grime", "older", "elder"] },
  { puzzleNumber: 3, words: ["steer", "route", "track", "trail"] },
  { puzzleNumber: 2, words: ["offer", "merit", "price", "prize"] },
  { puzzleNumber: 1, words: ["coach", "racer", "medal", "pedal"] },
];
