name: Lambda Function Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: cd backend && pip install -r requirements.txt

      - name: Package Lambda function
        run: cd backend/src/puzzle/ && zip -r ../../../lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Lambda function
        run: |
          if aws lambda get-function --function-name puzzle >/dev/null 2>&1; then
            aws lambda update-function-code \
              --function-name puzzle \
              --zip-file fileb://lambda_function.zip
          else
            aws lambda create-function \
              --function-name puzzle \
              --runtime python3.10 \
              --handler lambda_function.handler \
              --zip-file fileb://lambda_function.zip
              --role arn:aws:iam::255578370653:role/service-role/puzzle-role-tlnmgx98 \
              --environment Variables={ENVIRONMENT=production}
          fi
          
      - name: Clean up
        run: rm lambda_function.zip
